# Generated by Django 6.0.1 on 2026-03-24 22:29

import expedientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0013_usuario_access_gastos_usuario_access_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=expedientes.models.ruta_archivo_unica),
        ),
        migrations.AlterField(
            model_name='archivotemporal',
            name='archivo',
            field=models.FileField(upload_to=expedientes.models.ruta_archivo_temporal),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='condiciones_pago',
            field=models.CharField(choices=[('50_50', '50% Anticipo - 50% al Finalizar'), ('100_entrega', '100% Contra Entrega de Resultados'), ('contado', 'Pago de Contado')], default='50_50', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título del Proyecto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=expedientes.models.ruta_documento_unica),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador Master'), ('analista_sr', 'Abogado'), ('analista_jr', 'Analista')], db_index=True, default='analista_jr', max_length=20),
        ),
    ]
